name: Build & Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04(ubuntu-latest)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install
        run: |
          npm install -g yarn
          yarn
      - name: Build
        run: yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          folder: dist/spa
          branch: gh-pages
